default: &default
  adapter: spanner
  project: <%= ENV.fetch("GOOGLE_CLOUD_PROJECT") %>
  instance: <%= ENV.fetch("SPANNER_INSTANCE") %>
  database: <%= ENV.fetch("SPANNER_DATABASE") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development: &development
  <<: *default
  emulator_host: <%= ENV.fetch("SPANNER_EMULATOR_HOST", "") %>

test:
  <<: *development
  database: "test"

production:
  <<: *default
